vs_project/duendeMakeApp/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace duendeMakeApp.Models;

public partial class Producto
{
    public int ProductoId { get; set; }

    [Required(ErrorMessage = "El campo Descripcion es obligatorio.")]
    public string? Nombre { get; set; }

    [Required(ErrorMessage = "El campo Descripcion es obligatorio.")]
    public string? Descripcion { get; set; }

    [Required(ErrorMessage = "El campo Descripcion es obligatorio.")]
    public decimal? Precio { get; set; }

    [Required(ErrorMessage = "El campo Descripcion es obligatorio.")]
    public int? Cantidad { get; set; }

    [Required(ErrorMessage = "El campo Descripcion es obligatorio.")]
    public int? CategoriaId { get; set; }


    public bool? Estado { get; set; }

    public int? ImagenId { get; set; }

    public virtual Categoria? Categoria { get; set; }

    public virtual Imagen? Imagen { get; set; }

    public virtual ICollection<Carrito> Carritos { get; set; } = new List<Carrito>();

    public virtual ICollection<Catalogo> Catalogos { get; set; } = new List<Catalogo>();

    public virtual ICollection<Paquete> Paquetes { get; set; } = new List<Paquete>();

    public virtual ICollection<Subcategoria> Subcategoria { get; set; } = new List<Subcategoria>();
}

vs_project/duendeMakeApp/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using duendeMakeApp.Models;
using System.ComponentModel;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Drawing;
using duendeMakeApp.DAO;
using static System.Net.Mime.MediaTypeNames;

namespace duendeMakeApp.Controllers
{
    public class ProductosController : Controller
    {
        private readonly DuendeappContext _context;
        private List<Producto> productosCarrito = new List<Producto>();
        private static Usuario? _usuario;

        private readonly IHttpClientFactory _clientFactory;
        private readonly IHttpContextAccessor _httpContextAccessor;

        //private static string conStr;// = "Data Source=DESKTOP-993UODJ; Initial Catalog=DUENDEAPP; Integrated Security=true; Encrypt=False;";
        private static string? conStr;
        public ProductosController(DuendeappContext context, Usuario usuario, IHttpClientFactory clientFactory, IHttpContextAccessor httpContextAccessor)
        {
            _usuario = usuario;
            _context = context;
            _clientFactory = clientFactory;
            var serverName = _context.Database.GetDbConnection().DataSource;
            var databaseName = _context.Database.GetDbConnection().Database;
            var integratedSecurity = _context.Database.GetDbConnection().ConnectionString.Contains("Integrated Security=true");
            var encrypt = _context.Database.GetDbConnection().ConnectionString.Contains("Encrypt=true");
            var user = _context.Database.GetDbConnection().ConnectionString.Contains("User=");
            var password = _context.Database.GetDbConnection().ConnectionString.Contains("Password=");
            var conStrBuilder = new SqlConnectionStringBuilder
            {
                DataSource = serverName,
                InitialCatalog = databaseName,
                IntegratedSecurity = integratedSecurity,
                Encrypt = encrypt,
                UserID = user ? _context.Database.GetDbConnection().ConnectionString.Split("User=")[1].Split(";")[0] : "",
                Password = password ? _context.Database.GetDbConnection().ConnectionString.Split("Password=")[1].Split(";")[0] : ""
            };
            conStr = conStrBuilder.ConnectionString;
            Console.WriteLine(conStr);
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: Productos
        public async Task<IActionResult> Index(int? categoriaId, List<int> subcategoriaIds)
        {
            ViewBag.Usuario = UsuariosController.GetSessionUser(_httpContextAccessor, _context);
            ViewBag.categorias = _context.Categoria;
            ViewBag.subcategorias = _context.Subcategoria;

            IQueryable<Producto> duendeappContext = _context.Productos
                .Include(p => p.Imagen)
                .Include(p => p.Catalogos)
                .Include(p => p.Categoria)
                .Include(p => p.Subcategoria);

            if (categoriaId.HasValue)
            {
                duendeappContext = duendeappContext.Where(p => p.CategoriaId == categoriaId);
            }

            if (subcategoriaIds != null && subcategoriaIds.Count > 0)
            {
                duendeappContext = duendeappContext.Where(p => p.Subcategoria.Any(s => subcategoriaIds.Contains(s.SubcategoriaId)));
            }


            return View(await duendeappContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Imagen)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        public IActionResult Create()
        {
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "Nombre");
            ViewData["ImagenId"] = new SelectList(_context.Imagens, "ImagenId", "Nombre");

            ViewBag.Subcategoria = _context.Subcategoria.ToList();
                               
            return View("Create");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductoId,Nombre,Descripcion,Precio,Cantidad,CategoriaId,Estado,ImagenId")] Producto producto, List<int> SubIds)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                

                foreach (int subId in SubIds)
                {
                    Subcategoria sub = _context.Subcategoria.Find(subId);
                    if (sub != null)
                    {

                        producto.Subcategoria.Add(sub);
                    }
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "CategoriaId", producto.CategoriaId);
            ViewData["ImagenId"] = new SelectList(_context.Imagens, "ImagenId", "ImagenId", producto.ImagenId);
            return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "Nombre");
            ViewData["ImagenId"] = new SelectList(_context.Imagens, "ImagenId", "Nombre");
            ViewBag.Subcategoria = _context.Subcategoria.ToList();
            return View(producto);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductoId,Nombre,Descripcion,Precio,Cantidad,CategoriaId,Estado,ImagenId")] Producto producto)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ProductoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaId"] = new SelectList(_context.Categoria, "CategoriaId", "CategoriaId", producto.CategoriaId);
            ViewData["ImagenId"] = new SelectList(_context.Imagens, "ImagenId", "ImagenId", producto.ImagenId);
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.Categoria)
                .Include(p => p.Imagen)
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Productos == null)
            {
                return Problem("Entity set 'DuendeappContext.Productos'  is null.");
            }
            var producto = await _context.Productos.FindAsync(id);
            if (producto != null)
            {
                _context.Productos.Remove(producto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
          return (_context.Productos?.Any(e => e.ProductoId == id)).GetValueOrDefault();
        }




        public IActionResult index3()
        {

            
            _usuario = UsuariosController.GetSessionUser(_httpContextAccessor, _context); 
            ViewBag.Usuario = _usuario;

            int carrito = ObtenerCarritoPorUsuarioID(_usuario.UsuarioId);
            var oLista = new List<ProductoCarrito>();

            Console.WriteLine(carrito);
            using (SqlConnection conexion = new SqlConnection(conStr))
    

            {
                conexion.Open();
                SqlCommand cmd = new SqlCommand("ObtenerProductosEnCarrito", conexion);
                cmd.Parameters.AddWithValue("@CarritoID", carrito);
                cmd.Parameters.AddWithValue("@UsuarioID", _usuario.UsuarioId);
                cmd.CommandType = CommandType.StoredProcedure;

                using (var dr = cmd.ExecuteReader())
                {

                    while (dr.Read())
                    {
                        oLista.Add(new ProductoCarrito()
                        {

vs_project/duendeMakeApp/Views/Productos/Create.cshtml
@model duendeMakeApp.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Agregando producto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label"></label>
                <select asp-for="CategoriaId" class ="form-control" asp-items="ViewBag.CategoriaId"></select>
            </div>


            <div class="form-group">
                @*<label asp-for="Estado" class="control-label"></label>*@
                <input role="switch" type="hidden" asp-for="Estado" class="form-control" value="True" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImagenId" class="control-label"></label>
                <select asp-for="ImagenId" class ="form-control" asp-items="ViewBag.ImagenId"></select>
            </div>


            <div class="form-group">
                <label class="control-label">Seleccionar subcategorias:</label>
                <br>
                @foreach (var subs in ViewBag.Subcategoria)
                {
                    <label class="btn btn-secondary">
                        <input type="checkbox" name="SubIds" value="@subs.SubcategoriaId"> @subs.Nombre
                    </label>
                }
            </div>

            <div class="form-group">
                <input type="submit" value="Agregar producto" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-danger">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

vs_project/duendeMakeApp/Views/Productos/Delete.cshtml
@model duendeMakeApp.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.CategoriaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen.ImagenId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

vs_project/duendeMakeApp/Views/Productos/Details.cshtml
@model duendeMakeApp.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria.CategoriaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen.ImagenId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ProductoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

vs_project/duendeMakeApp/Views/Productos/Index.cshtml
@model IEnumerable<duendeMakeApp.Models.Producto>

@{
    ViewData["Title"] = "Index";
}
<style>
    .fade-in {
        opacity: 1;
        transition: opacity 0.5s ease-in-out;
    }

    .fade-out {
        opacity: 0;
        transition: opacity 0.5s ease-in-out;
    }
</style>

@if (!string.IsNullOrEmpty(TempData["mensaje"] as string))
{
    <div class="alert alert-info fade-in" id="mensajeDiv">@TempData["mensaje"]</div>
    TempData.Remove("mensaje");
    <script>
        // JavaScript para ocultar el mensaje después de 3 segundos
        setTimeout(function () {
            var mensajeDiv = document.getElementById('mensajeDiv');
            mensajeDiv.classList.remove('fade-in');
            mensajeDiv.classList.add('fade-out');
        }, 3000); // 3000 milisegundos = 3 segundos
    </script>
}

<div class="container">
    <h1>Productos</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <form asp-controller="Productos" asp-action="Index" method="get" class="form-inline">


                        <div class="form-group">
                            <select class="form-control" id="categoriaId" name="categoriaId">
                                <option value="">Todas las categorías</option>
                                @foreach (Categoria cat in ViewBag.categorias)
                                {
                                    <option value="@cat.CategoriaId">@cat.Nombre</option>
                                }
                            </select>
                        </div>


                        <div class="form-group">
                            <select class="form-control" id="subcategoriaId" name="subcategoriaIds">
                                <option value="">Todas las subcategorías</option>
                                @foreach (Subcategoria subcat in ViewBag.subcategorias)
                                {
                                    <option value="@subcat.SubcategoriaId">@subcat.Nombre</option>
                                }
                            </select>
                        </div>



                        <button type="submit" class="btn btn-primary ml-2">Filtrar</button>
                    </form>
                    <input class="form-control" id="myInput" type="text" placeholder="Buscar..">
                </li>
            </ul>
                
            <form class="form-inline my-2 my-lg-0">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @try{
                    @if(ViewBag.Usuario.TipoId == 1)
                    {  
                        <a class="btn btn-primary" asp-action="Create">Agregar producto</a>
                    }
                }
                catch(Exception e){}
            </form>
        </div>
    </nav>

    <br>

    <div id="myDIV" class="row">
        @foreach (Producto producto in Model)
        {
            <div id="content" class="col-md-4">
                @if (producto.Estado == false || producto.Cantidad < 1)
                {
                    <p class="badge badge-danger">Sin stock</p>
                }
                else
                {
                    <p class="badge badge-success">En stock</p>

                }
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" alt="Thumbnail [100%x225]"
                         style="height: 225px; width: 100%; display: block; object-fit:cover;" src= "@producto.Imagen.Url" data-holder-rendered="true">
                    <div class="card-body">
                        <p class="card-title"><strong>@producto.Nombre</strong></p>
                        <p class="card-text">
                            @producto.Descripcion
                            <br />
                            @foreach (Catalogo catalogo in producto.Catalogos)
                            {
                                <span class="badge badge-info">
                                    @catalogo.Nombre
                                </span>
                            }
                        </p>
                        <p class="card-text">@producto.Precio ₡</p>
                        <div class="d-flex justify-content-between align-items-center">

                                <div class="btn-group">
                                 @if (producto.Estado == true && producto.Cantidad > 0)
                                {
                                    try
                                    {
                                        if (ViewBag.Usuario.TipoId == 2)
                                        {
                                            <a class="btn btn-secondary" asp-action="agregarAlCarrito" asp-route-id="@producto.ProductoId">Agregar al carrito</a>
                                        }
                                    }
                                    catch (Exception e)
                                    {
                                        <a class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#loginModal" data-dismiss="modal">Agregar al carrito</a>
                                    }
                                }
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#@producto.ProductoId">Ver</button>

                                  </div>        
                                
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="@producto.ProductoId" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">@producto.Nombre</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div>
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <div id="carousel-@producto.ProductoId" class="carousel slide" data-ride="carousel">
                                                    <div class="carousel-inner">
                                                        <div class="carousel-item active" style="">
                                                            <article class="card" style="max-width: 18rem;">
                                                                <img class="card-img-top"
                                                                        style="height: 300px; width: 300px; display: block;object-fit:cover;"
                                                                        src="@producto.Imagen.Url"
                                                                        data-holder-rendered="true">
                                                            </article>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="row">
                                                <dt>
                                                    Nombre: <br>
                                                </dt>
                                                <dd>
                                                    @producto.Nombre
                                                </dd>
                                                <dt>
                                                    Descripcion: <br>
                                                </dt>
                                                <dd class="col-sm-10">
                                                    @producto.Descripcion
                                                </dd>
                                                <dt>
                                                    @Html.DisplayNameFor(producto => producto.Precio)
                                                </dt>
                                                <dd class="col-sm-10">
                                                    @producto.Precio ₡
                                                </dd>
                                            </td>
                                        </tr>
                                     </tbody>
                                </table>
                            </div>
                        </div>
                        @try
                        {
                            @if (ViewBag.Usuario.TipoId == 1)
                            {
                                <div class="modal-footer">
                                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@producto.ProductoId">Eliminar</a>
                                    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@producto.ProductoId">Editar</a>
                                    
                                </div>
                            }                   
                        }
                        catch (Exception)
                        {

                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

vs_project/duendeMakeApp/Views/Productos/mostrarCarrito.cshtml
@model IEnumerable<duendeMakeApp.Models.Producto>

@{
    ViewData["Title"] = "Index";
}

        <H1>Carrito de compras</H1>
 
        
        
        <table class="table table-striped ">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Precio</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Descripcion</td>
                        <td>@item.Precio</td>


                    </tr>

                }
            </tbody>
        </table>