vs_project/duendeMakeApp/Controllers/AgendasController.cs
using duendeMakeApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace duendeMakeApp.Controllers
{
    public class AgendasController : Controller
    {
        private readonly DuendeappContext _context;
        private List<Producto> productosCarrito = new List<Producto>();
        private static Usuario? _usuario;

        private readonly IHttpClientFactory _clientFactory;
        private readonly IHttpContextAccessor _httpContextAccessor;

        //private static string conStr;// = "Data Source=DESKTOP-993UODJ; Initial Catalog=DUENDEAPP; Integrated Security=true; Encrypt=False;";
        private static string? concStr;

        private List<IAgendaEntry> agendaEntries = new List<IAgendaEntry>();

        public AgendasController(DuendeappContext context, Usuario usuario, IHttpClientFactory clientFactory, IHttpContextAccessor httpContextAccessor)
        {
            _usuario = usuario;
            _context = context;
            _clientFactory = clientFactory;
            var serverName = _context.Database.GetDbConnection().DataSource;
            var databaseName = _context.Database.GetDbConnection().Database;
            var integratedSecurity = _context.Database.GetDbConnection().ConnectionString.Contains("Integrated Security=true");
            var encrypt = _context.Database.GetDbConnection().ConnectionString.Contains("Encrypt=true");
            var user = _context.Database.GetDbConnection().ConnectionString.Contains("User=");
            var password = _context.Database.GetDbConnection().ConnectionString.Contains("Password=");
            var conStrBuilder = new SqlConnectionStringBuilder
            {
                DataSource = serverName,
                InitialCatalog = databaseName,
                IntegratedSecurity = integratedSecurity,
                Encrypt = encrypt,
                UserID = user ? _context.Database.GetDbConnection().ConnectionString.Split("User=")[1].Split(";")[0] : "",
                Password = password ? _context.Database.GetDbConnection().ConnectionString.Split("Password=")[1].Split(";")[0] : ""
            };
            concStr = conStrBuilder.ConnectionString;
            Console.WriteLine(concStr);
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            ViewBag.Usuario = UsuariosController.GetSessionUser(_httpContextAccessor, _context);
            ViewBag.AgendaEntries = new List<AgendaEntry>();  // O carga las entradas reales aquí
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult AgregarEntrada(string fecha,string asunto, string detalle, int duracion)
        {
            DateTime fechaInicio;
            try
            {
                fechaInicio = DateTime.Parse(fecha);
            }
            catch (Exception)
            {
                fechaInicio = DateTime.Now;
            }
            if(asunto=="entregar pedido")
            {
                //crear agenda con la fecha actual, los dias de entrega son martes, jueves y sabado. Solo se puede hacer esos dias entrega,
                //si se aprueba un dia que no es martes, jueves o sabado, se debe hacer la entrega el dia martes, jueves o sabado mas cercano
                if (fechaInicio.DayOfWeek == DayOfWeek.Tuesday || fechaInicio.DayOfWeek == DayOfWeek.Thursday || fechaInicio.DayOfWeek == DayOfWeek.Saturday)//si es martes, jueves o sabado se entrega el mismo dia 
                {
                    fechaInicio = fechaInicio;
                }
                else
                {
                    while (fechaInicio.DayOfWeek != DayOfWeek.Tuesday && fechaInicio.DayOfWeek != DayOfWeek.Thursday && fechaInicio.DayOfWeek != DayOfWeek.Saturday)
                    {
                        fechaInicio = fechaInicio.AddDays(1);
                    }
                }
            }
            // Agregar la entrada a la base de datos
            using (SqlConnection conexion = new SqlConnection(concStr))
            {
                conexion.Open();
                SqlCommand cmd = new SqlCommand("INSERT INTO Agenda (Detalle, FechaInicio, DuracionHoras, TipoEntrada) VALUES (@Detalle, @FechaInicio, @DuracionHoras, @TipoEntrada)", conexion);
                //cmd.Parameters.AddWithValue("@UsuarioID", _usuario?.UsuarioId);
                cmd.Parameters.AddWithValue("@Detalle", detalle);
                cmd.Parameters.AddWithValue("@FechaInicio", fechaInicio);
                cmd.Parameters.AddWithValue("@DuracionHoras", duracion);
                cmd.Parameters.AddWithValue("@TipoEntrada", asunto);
                cmd.ExecuteNonQuery();
            }
            // redirigir a la página de agenda index
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult EliminarEntrada(int idEvento)
        {
            // Eliminar la entrada de la base de datos
            using (SqlConnection conexion = new SqlConnection(concStr))
            {
                conexion.Open();
                SqlCommand cmd = new SqlCommand("DELETE FROM Agenda WHERE AgendaID = @AgendaID", conexion);
                cmd.Parameters.AddWithValue("@AgendaID", idEvento);
                cmd.ExecuteNonQuery();
            }
            // redirigir a la página de agenda index
            return RedirectToAction("Index");
        }

        public List<IAgendaEntry> GetAgendas ()
        {
            List<IAgendaEntry> agendaEntries = new List<IAgendaEntry>();

            using (SqlConnection conexion = new SqlConnection(concStr))
            {
                conexion.Open();
                SqlCommand cmd = new SqlCommand("SELECT * FROM Agenda", conexion);

                using (var dr = cmd.ExecuteReader())
                {
                    while (dr.Read())
                    {
                        DateTime? fechaInicio = null;

                        try
                        {
                            if (dr["FechaInicio"] != DBNull.Value)
                            {
                                fechaInicio = (DateTime?)dr["FechaInicio"];
                            }
                        }
                        catch (InvalidCastException)
                        {
                            fechaInicio = null;
                        }
                        AgendaEntry agenda = new AgendaEntry()
                        {
                            AgendaID = (int)dr["AgendaID"],
                            UsuarioID = (int)dr["UsuarioID"],
                            Detalle = (string)dr["Detalle"],
                            FechaInicio = fechaInicio,
                            DuracionHoras = (int)dr["DuracionHoras"]
                        };
                        if ((string)dr["TipoEntrada"] == "entregar pedido")
                        {
                            agendaEntries.Add(new EntregarPedidoDecorator(agenda));
                        }
                        if ((string)dr["TipoEntrada"] == "revisar inventario")
                        {
                            agendaEntries.Add(new RevisarInventarioDecorator(agenda));
                        }
                    }
                }
            }

            return agendaEntries;
        }


        public ActionResult GetAgendaEvents()
        {
            List<IAgendaEntry> agendaEvents = new List<IAgendaEntry>();

            using (SqlConnection conexion = new SqlConnection(concStr))
            {
                conexion.Open();
                SqlCommand cmd = new SqlCommand("SELECT * FROM Agenda", conexion);

                using (var dr = cmd.ExecuteReader())
                {
                    while (dr.Read())
                    {
                        DateTime? fechaInicio = null;

                        try
                        {
                            if (dr["FechaInicio"] != DBNull.Value)
                            {
                                fechaInicio = (DateTime?)dr["FechaInicio"];
                            }
                        }
                        catch (InvalidCastException)
                        {
                            fechaInicio = null;
                        }
                        AgendaEntry agenda = new AgendaEntry()
                        {
                            AgendaID = (int)dr["AgendaID"],
                            //UsuarioID = (int)dr["UsuarioID"],
                            Detalle = (string)dr["Detalle"],
                            FechaInicio = fechaInicio,
                            DuracionHoras = (int)dr["DuracionHoras"]
                        };
                        if ((string)dr["TipoEntrada"] == "entregar pedido")
                        {
                            agendaEvents.Add(new EntregarPedidoDecorator(agenda));
                        }
                        if ((string)dr["TipoEntrada"] == "revisar inventario")
                        {
                            agendaEvents.Add(new RevisarInventarioDecorator(agenda));
                        }
                        if ((string)dr["TipoEntrada"] == "maquillajes")
                        {
                            agendaEvents.Add(new RevisarInventarioDecorator(agenda));
                        }
                    }
                }
            }

            return formatoJsonEvent(agendaEvents);
        }

        public ActionResult formatoJsonEvent(List<IAgendaEntry> agendaEvents)
        {

vs_project/duendeMakeApp/Views/Agendas/Index.cshtml
@{
    ViewData["Title"] = "Index";
    //definir ViewBag.id
    ViewBag.id = 0;
}

@if(ViewBag.Usuario.Tipo.Tipo == "admin")
{
    <style>
        /* Custom root property values */
        :root {
            --fc-small-font-size: .85em;
            --fc-page-bg-color: #fff;
            --fc-neutral-bg-color: hsla(0,0%,82%,.3);
            --fc-neutral-text-color: grey;
            --fc-border-color: #ddd;
            --fc-button-text-color: #fff;
            --fc-button-bg-color: #202124;
            --fc-button-border-color: #2c3e50;
            --fc-button-hover-bg-color: #1e2b37;
            --fc-button-hover-border-color: #1a252f;
            --fc-button-active-bg-color: #1a252f;
            --fc-button-active-border-color: #151e27;
            --fc-event-bg-color: #3788d8;
            --fc-event-border-color: #3788d8;
            --fc-event-text-color: #fff;
            --fc-event-selected-overlay-color: rgba(0,0,0,.25);
            --fc-more-link-bg-color: #d0d0d0;
            --fc-more-link-text-color: inherit;
            --fc-event-resizer-thickness: 8px;
            --fc-event-resizer-dot-total-width: 8px;
            --fc-event-resizer-dot-border-width: 1px;
            --fc-non-business-color: hsla(0,0%,84%,.3);
            --fc-bg-event-color: #8fdf82;
            --fc-bg-event-opacity: 0.3;
            --fc-highlight-color: rgba(188,232,241,.3);
            --fc-today-bg-color: #A2D94A;
            --fc-now-indicator-color: red;
        }

        body {
            font-size: var(--fc-small-font-size);
            background-color: var(--fc-page-bg-color);
        }

        .fc-dayGridMonth-button, .fc-timeGridWeek-button, .fc-timeGridDay-button, .fc-listWeek-button {
            color: var(--fc-button-text-color);
            background-color: var(--fc-button-bg-color);
            border-color: var(--fc-button-border-color);
        }

            .fc-dayGridMonth-button:hover, .fc-timeGridWeek-button:hover, .fc-timeGridDay-button:hover, .fc-listWeek-button:hover {
                background-color: var(--fc-button-hover-bg-color);
                border-color: var(--fc-button-hover-border-color);
            }

            .fc-dayGridMonth-button:active, .fc-timeGridWeek-button:active, .fc-timeGridDay-button:active, .fc-listWeek-button:active {
                background-color: var(--fc-button-active-bg-color);
                border-color: var(--fc-button-active-border-color);
            }
    </style>
    <div id='calendar'></div>

    <!-- Agrega el siguiente código para el modal -->
    <div class="modal fade" id="myModalSinEventos" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="exampleModalLabel">Evento</h3>
                    <button type="button" id ="x2"class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form asp-action="AgregarEntrada">
                        <p id="fechaSeleccionada" name="fecha"></p>
                        <input class="form-control" id="fecha" name="fecha" rows="3" >
                        <div class="form-group">
                            <label for="asunto">Asunto:</label>
                            @*mostrar los asunto disponible, maquillajes, entregar pedido y revisar inventar*@
                             <select class="form-control" id="asunto" name="asunto">
                                <option value="maquillajes">Maquillajes</option>
                                <option value="entregar pedido">Entregar pedido</option>
                                <option value="revisar inventario">Revisar inventario</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="detalle">Detalle</label>
                            <textarea class="form-control" id="detalle" name="detalle" rows="3" placeholder="Ingrese el detalle"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="duracion">Duracion:</label>
                            <input class="form-control" id="duracion" name="duracion" rows="3" placeholder="Ingrese la duracion">
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Agregar a agenda" class="btn btn-primary" />
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    @* <a id="prueba" class="btn btn-primary" data-dismiss="modal" asp-controller="Agendas" asp-action="AgregarEntrada">Guardar</a> *@
                    <button type="button" id="cerrarBtnSinEvento" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal para eventos -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="exampleModalLabel">Evento</h3>
                    <button type="button" id="x" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form asp-action="EliminarEntrada">
                        <!-- Mostrar la información del evento -->
                        <p id="idEvento" name="idEvento"></p>
                        <input class="form-control" id="idEvento2" name="idEvento" rows="3">
                        <p id="fechaSeleccionada2" name="fecha2"></p>
                        <input class="form-control" id="fecha2" name="fecha2" rows="3">
                        <div class="form-group">
                            <label for="asunto">Asunto:</label>
                            <!-- Mostrar los asuntos disponibles para eventos -->
                            <input class="form-control" id="asunto2" name="asunto2" rows="3" placeholder="Ingrese la duración">
                            @* <select class="form-control" id="asunto2" name="asunto2">
                                <option value="maquillajes">Maquillajes</option>
                                <option value="entregar pedido">Entregar pedido</option>
                                <option value="revisar inventario">Revisar inventario</option>
                            </select> *@
                        </div>
                        <div class="form-group">
                            <label for="detalle">Detalle</label>
                            <textarea class="form-control" id="detalle2" name="detalle2" rows="3" placeholder="Ingrese el detalle"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="duracion">Duración:</label>
                            <input class="form-control" id="duracion2" name="duracion2" rows="3" placeholder="Ingrese la duración">
                        </div>
                        <div class="form-group">
                            <!-- Agregar cualquier botón o acción adicional para eventos -->
                            @* <input type="submit" value="Actualizar evento" class="btn btn-primary" /> *@
                            <input type="submit" value="Eliminar de agenda" class="btn btn-danger" />
                            @* <button type="button" id="eliminarBtn" class="btn btn-danger">Eliminar evento</button> *@
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" id="cerrarBtn" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script>
        var eventoslist = @Html.Raw(Json.Serialize(ViewBag.EventInfo));
        var idEvento = 0
        var evento;
        document.getElementById("x2").addEventListener("click", function () {
            $('#titulo').val("");
            $('#myModalSinEventos').modal('hide');
        });
        document.getElementById("cerrarBtnSinEvento").addEventListener("click", function () {
            $('#titulo').val("");
            $('#myModalSinEventos').modal('hide');
        });
        document.getElementById("x").addEventListener("click", function () {
            $('#titulo').val("");
            $('#myModal').modal('hide');
        });
        document.getElementById("cerrarBtn").addEventListener("click", function () {
            $('#titulo').val("");
            $('#myModal').modal('hide');
        });


        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            // json con los eventos existentes en la base de datos, GetAgendaEvents es el método que se encuentra en el controlador
            var eventos = '/Agendas/GetAgendaEvents';
            
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                nowIndicator: true,
                headerToolbar: {
                    left: 'prev,next,today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },
                buttonText: {
                    today: 'Hoy',
                    month: 'Mes',
                    week: 'Semana',
                    day: 'Día'
                },
                navLinks: true,
                dateClick: function (info) {
                    // dirigir al modal para agregar un evento
                    $('#titulo').val("");
                    $('#fecha').val(info.dateStr);
                    $('#myModalSinEventos').modal('show');
                },

                // Combina ambos manejadores de eventos eventClick en uno solo
                eventClick: function (info) {
                    $('#titulo').val("");
                    $('#titulo').val(info.event.title);
                    if (info.event.id) {
                        idEvento = info.event.id;
                        console.log('ID:' + idEvento);
                        evento = info.event;
                        console.log(evento);
                        // evento = eventoslist.find(x => x.id === idEvento);
                        var duracion = 0;
                        var fechaInicio = evento.start;
                        var fechaFin = evento.end;
                        if (fechaFin != null) {
                            duracion = fechaFin.getHours() - fechaInicio.getHours();
                        }
                        //usar datos del evento
                        $('#idEvento').text('Id: ');
                        $('#idEvento2').val(evento.id);
                        $('#fechaSeleccionada2').text('Fecha: ');
                        $('#fecha2').val(evento.start.toDateString());
                        $('#asunto2').val(evento.title);
                        $('#detalle2').val(evento.extendedProps.detalle);
                        $('#duracion2').val(duracion);
                        $('#myModal').modal('show');
                        // $('#myModal').modal('show');
                    } else {
                        idEvento = 0;
                        $('#myModalSinEventos').modal('show');
                    }
                },
                editable: false,
                selectable: false,
                selectMirror: false,
                dayMaxEvents: true,

                eventDidMount: function (info) {
                    // Acciones cuando se monta un evento
                    //alert(info.event.title);
                },
                // events: eventos

                events: '/Agendas/GetAgendaEvents',
                eventAfterAllRender: function () {
                     // Load the partial view after rendering the calendar
                    $.get('/Agendas/GetAgendaEvents', function (data) {
                         $('#agendaEntriesContainer').html(data.PartialView);
                    });
                }
            
            });

            calendar.render();
        });


    </script>
}
else
{
    <div class="alert alert-danger">Acceso ddenegado.</div>
}